language: php
php:
  - 5.5
 # - 5.6


branches:
 except:
   - test
   
env:
  - M1=one
  - M2=two
  #global:
   # - NOUVOLA_PLAN_ID=3210
    #- XUNIT_FILE=./shippable/testresults/results.xml
  #matrix:
   # - secure: KU8TCo4gW3ChSAVMGImByWRpAegZdtHZVw5Hqp0+QiytQBB+PlAIqayZjzK5ca7dG9qE2kl92IxAYCBgs+Q3AV5jwIICatVpvYZ3z+mnvNMPf1tGYo8nt8+SkWkRKwvEpG5t6BPdtOnWeZ8snK2mgeanAXRTz1rCXzS8Pf8CZXim3z4b7idsBULBMNyWtMju8NSpHwdaIwOaMDAqyfZnt/h3J9KcgxIxGZ7A629JDHzUAPoFYrZwiJQ4luvgZoQ/l7I34uQihQq1sKzIzysmOXHTwCeNFG5dt/V/t90j17SMD98PbaqCqG0ydnJ8y4GGGlk5kwY5+1fj+kLgjXRQxA==
    
timeout: 1
  #matrix:
  #  - secure: #FFBcn4HfaggIDYZMJBPAJ8AGeiyO/XNmgOfymwhvhMUdADd5tJK7fbr5cn+mxJ6g7yRpxXhpx4orxy3kMUJRlWfgkjbaod5kp4UJMLe6IebDO9OG4OVVJorFX5A/LfhaiYWiii/WsOE5miuXol0XuuJluKuVOUkKcFq9DylehZH6sP40Re3YprEmRojLJ55nKc4e1g/sOR0Ns9ZvfmtyKny4dgOfOoF8tSOLrkqiv8CGjLbTTtGIhslQ29myUFtO59IZCJq/90wnvCgBHp5poE8P1ZEjfHKO7iQDZZ/DBy81ZrWuHtxhSfQ3jH/+5+7CKH15dRAZeegILPZi3whYsQ==
   # - API_CALL="-X POST -H 'Content-Type: application/json' -H 'x-api:"" "${NOUVOLA_API_KEY}"' https://divecloud.nouvola.com/api/v1/plans/"${NOUVOLA_PLAN_ID}"/run"

matrix:
 include:
   - php: 5.6
  
 allow_failures:
    - php: 5.5 
      env:
        - M1=one
    - php: 5.5
      env:
        - M2=two
   
build:
 ci: 
  - sleep 123m
  - sudo apt-get update
  - echo $NOUVOLA_PLAN_ID and $key1
  - if [ "$SHIPPABLE_PHP_VERSION" == "5.5" ]; then foobar; fi
